### PR TITLE
:sparkles: Player's theme options + Custom CSS field

### PR DESCRIPTION
**Pull request by CosmoMyzrailGorynych**
* Player now uses themable SVG symbols (icons from feathericons.com)
* All the buttons init their state on page load
* Added several theme controls, revisited the display of buttons and the slider
  * Transparent background can be used to blend in other pages. 
* Added a simple CSS field
* Tweaked text styles a bit inside the player

изображение

Example usage of transparent background on itch.io (still needs a bit of custom CSS on itch.io page):

изображение

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
btw here's another album to your itch collection hehe https://comigo.itch.io/music-loops

**Comment by blackle** [comment]
added the album to the collection!

hmm it doesn't seem to be possible to get the original white-with-border button style with these changes. trying to think how we can support this. I would like the default style to remain bandcamp-like. maybe we could have "inverted buttons" and "borderless buttons" as added options to get to your style?

**Comment by CosmoMyzrailGorynych** [comment]
But those white buttons suck :c There's nothing cool in unthemable controls that look like they came from 2000s, even if bandcamp still uses such buttons.

I think what should be done is making icons either black or white, based on their background's liminocity. And I need to think about adding borders without adding another color controls.

**Comment by blackle** [comment]
Well, it is all up to preference. I do think there should be lots of configuration options, but I would like to keep the "bandcamp by default" style.

How about we have separate colour controls for the buttons? I know a user could set the button colour manually with CSS, but colour pickers are a better experience generally.

**Comment by blackle** [comment]
I made a branch that adds extra colour pickers. Looks like this:

Screenshot from 2022-03-14 20-01-46

https://github.com/blackle/blamscamp/tree/extra_colours

If you want I can merge this in and add in the colour pickers after. I think it would be really cool if a person could get a vanilla bandcamp look and your cool rounded button+glowy shadow style without needing to touch CSS

**Comment by CosmoMyzrailGorynych** [comment]
>  I do think there should be lots of configuration options

My problem with lots of color inputs is that they are a pain to use on Windows — we can't even paste a hex code from elsewhere x_x And are tons of configs always good?
I though about making two-way inputs (color+text) before, but my implementation wasn't clean enough to go into production.
I also thought about making a dropdown with selectable themes initially (bandcamp style/neon/flat/whatever).

I've pushed a more slim version recently, with buttons' background being lighter if borders are enabled (flat white semi-transparent gradient is used for this effect)

Automatic icon colors can be seen here as well.

Снимок экрана 2022-03-15 104530
Снимок экрана 2022-03-15 104444

**Comment by CosmoMyzrailGorynych** [comment]
(still not fully possible to replicate bandcamp look, though)

Also, in your branch, I think this should be named more specifically, like "Buttons"

изображение

**Comment by blackle** [comment]
About colour input: the way it's implemented is dependent on the operating system and web browser. On windows and firefox it pops up the old ms paint colour picker, and on chrome it's a much nicer inline colour picker. I'm probably going to add a js colour picker as a dependency, which should make the experience the same for everyone. That way we could also update colours in real time.

I do agree too many configs are bad, but I don't think we're in a rough spot yet. I'm thinking the custom button colours could go behind a checkbox

The drop-down theme idea is pretty interesting, especially because it means it would make room for a windows 95 theme :3

> Also, in your branch, I think this should be named more specifically, like "Buttons" or "Buttons' background"

calling it buttons would work!


If there's nothing else you want to put in this PR, how about we merge it and I'll figure out how to give the option for the classic bandcamp style, because I do want to keep that an option for people

**Comment by blackle** [comment]
added a colour picker over here: #10 
instantly makes the colour picking much more user friendly on firefox.

**Comment by CosmoMyzrailGorynych** [comment]
Ok, let's merge in all the three branches :rofl:
Do you need assistance in something??

**Pull request merged**
