### PR TITLE
:sparkles: Import ZIP files back into blamscamp

### PR DESCRIPTION
**Pull request by CosmoMyzrailGorynych**
💪

Quite a messy solution for storing imported files, but that's how it is unless a UI framework like Svelte or Riot is introduced. I can make a rewrite in Svelte after my PRs are merged if you want. Adding further functionality will probably result in a bigger mess.

~~This PR _should_ be conflict-less with my other PRs, but ping me if there are some and you need help.~~

Ok, there is a merge conflict between my conditional blocks and zip import, but resolving should be pretty obvious.

import

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
Sure, the player will be vanilla. I don't see any reasons to be otherwise as it is feature-complete already, smol, and maintainable. That's the editor part that needs to be more extensible.

The obvious thing that needs cleaning is working with inputs themselves. I'm already making some work in this direction (framework-free). Maybe I will eventually replace most of the `serialize` method with one loop over HTML form's `elements` property.

**Comment by CosmoMyzrailGorynych** [comment]
The problem I see in UI mainly comes from this PR... as you need to store files somewhere separately from HTML markup as you can't quite write into `input[type="file"]`. And this causes the need for a more robust templating process that will base itself on a data model separate from the markup. I would also add song sorting buttons, and making them with the current setup might be a pain.

**Comment by CosmoMyzrailGorynych** [comment]
I may or may not come up with a tiny model-to-view template engine that supports loops as well 🤔 This would simplify most of the stuff as everything else can be made with event delegation.

**Comment by blackle** [comment]
cool. could you do that in a separate PR? I'm good to merge this in, just need the conflict fixed

**Comment by CosmoMyzrailGorynych** [comment]
Already doing this. Well, I'm on the edge of falling asleep, but I have a plan on how to do the UI without overcomplicated mostrosities. Loops will be handled with array's `map` method lol. Here're the bits of code explaining my plans:

image

image
(This will be rendered into HTML with the template above on any change inside the song list. Data binding will be done with event delegation.)

Also a sneak-peek on other stuff 👀 
image

I will probably send a PR tomorrow.

**Comment by blackle** [comment]
very nice! the [:[template]:] format was just something I arbitrarily picked. there may be a simpler format that has a better regex. very excited to see the code!

**Comment by blackle** [comment]
just a heads up: I pushed a commit to simplify the template format from:

[:[field]:]
[:if[album]:]

to:

<:field:>
<:if:album:>

it massively simplifies the regex, much fewer backslash escapes

**Comment by CosmoMyzrailGorynych** [comment]
@blackle I've resolved the conflict and merged in the head of this repo.
This PR just hanging here prevents me from building further stuff (major UI improvements will affect serialization/deserialization process), so I would like to see this PR merged sooner than later 😅

**Comment by blackle** [comment]
merged!

**Pull request merged**
